### ISSUE TITLE
Feature Request: CtrlP integration

### ISSUE THREAD

**Issue by felixSchl** [clausreinke/typescript-tools#37]
File navigation could be a lot smoother when integrated with CtrlP. The coupling may seem odd, but should be worth the trade off. For reference, the [omnisharp](https://github.com/nosami/Omnisharp) guys also decided to go down that route.

**Comment by clausreinke** [comment]
Having looked into the CtrlP extension protocol again, I don't think it will be a good fit for us: it wants us to create a simple list of strings, handles the selection, then passes the selected string to our action function. 

For filenames, that just about works, but I don't see the advantage against what we have. 

For more general "find symbols that look like" search, which I've just added in the `testing_ts1.4` branch (`:TSSnavigateTo symbol`), the protocol seems to be too simple: even after selecting a symbol, there are still several possible sources to jump to, so I need to preserve more information than the string used for selection.

I'm not happy with my own implementation, either (uses completion to identify the symbol to search for, then opens a menu for the remaining ambiguities), and the file and symbol queries are currently separate, but I don't think I'll add anything to our plugin specific to CtrlP support.

Note to self: if reconsidering this decision in the future, also check [unite](https://github.com/Shougo/unite.vim) instead of [ctrlp](https://github.com/kien/ctrlp.vim).
