### ISSUE TITLE
Parameter completion

### ISSUE THREAD

**Issue by dani-h** [clausreinke/typescript-tools#46]
Would it be/is it possible to complete/list function parameters for the Vim plugin? README.md mentions the function TSScompleteFunc, but it's not entirely clear what it does.

**Comment by clausreinke** [comment]
`TSScompleteFunc` computes the information used in insert-mode completion (`:help omnifunc`).

I've just added (in branch `testing_ts1.4`) name and type to the documentation info that is displayed in the completion preview window, when you do `:setlocal completeopt+=preview`. Since the preview window stays open after you're chosen a completion, that gives you access to the same parameter info you have in the completion menu, while you're writing the parameters.

Better support is possible, but not immediately on the roadmap: Since completion can only insert placeholders, we'd need some placeholder navigation and replacement code, probably from one of the Vim snippets plugins, and there are so many to choose from..

**Comment by dani-h** [comment]
Aha, well that's good enough for now. On a side note: Why aren't TSS tools and the Vim plugin split into two different repos?

**Comment by zlumer** [comment]
+1 for separate repos.
I'm subscribed to TSS, but not interested in any Vim activity. It would be easier to manage notifications with 2 different projects.

**Comment by clausreinke** [comment]
not sure why those asking for separate repos can't use a separate issue.. #50.

**Comment by clausreinke** [comment]
Back to the issue here: I'd be interested to learn which of the many snippets plugins (with placeholder support) people use these days, and how they are typically integrated with insert mode completion plugins.

**Comment by clausreinke** [comment]
to be continued in clausreinke/typescript-tools.vim#2
